### ISSUE TITLE
Provide project-specific `rustfmt` and `.editorconfig` configurations

### ISSUE THREAD

**Issue by eirnym** [boozook/playdate#235]
Otherwise contributing could be painful

**Comment by boozook** [comment]
Rustfmt config is [here](https://github.com/boozook/playdate/blob/main/rustfmt.toml)

**Comment by eirnym** [comment]
I see. `rustfmt` is required from nightly. 

EditorConfig would be useful though to make editors format in more or less the same way (at least what's about the tabs and spaces)

**Comment by boozook** [comment]
Fixed in https://github.com/boozook/playdate/commit/46b9ff4a647f9f1d8912aedaf0d1c0a9df4c82d2.
