### ISSUE TITLE
Hello world example seems to be broken

### ISSUE THREAD

**Issue by ishche** [boozook/playdate#349]
After following the steps on https://github.com/boozook/playdate/blob/main/cargo/README.md#hello-world I've got an error message:
```
error: no matching package named 'playdate' found
```

up:
System Version: macOS 14.1 (23B74)
cargo-playdate: 0.4.10

**Comment by boozook** [comment]
@ishche Could you try `cargo check` before `cargo playdate run` please?

**Comment by boozook** [comment]
@ishche Seems to fixed, I can't reproduce with [`cargo-playdate v0.5.0-beta.6`](https://crates.io/crates/cargo-playdate/0.5.0-beta.6). Could you try it plz? You can install it with `cargo install cargo-playdate@v0.5.0-beta.6`.
Could be awesome if you confirm that it fixed finally ❤️‍🔥

**Comment by ishche** [comment]
I can't reproduce, too. Thank you!
