### ISSUE TITLE
cli::tests::init_args_before_cmd fails on windows

### ISSUE THREAD

**Issue by notpeter** [boozook/playdate#352]
Clean checkout on Windows 11 pro. Running `cargo test` and `cli::tests::init_args_before_cmd` fails.

I think CLI tests are not being run under CI.

<details><summary>Test run output</summary>
<pre>
running 13 tests
test proc::reader::format::tests::message_format_new ... ok
test proc::reader::format::tests::message_format_old_a ... ok
test proc::reader::format::tests::message_format_old_b ... ok
test proc::reader::format::tests::msg_message_format_old ... ok
test cli::tests::args_global ... ok
test init::tests::full_metadata_is_valid ... ok
test cli::tests::args_commands_not_missed ... ok
test cli::tests::args_build ... ok
test cli::tests::args_new ... ok
test cli::tests::args ... ok
test cli::tests::init_args_before_cmd ... FAILED
test cli::tests::init_cargo ... ok
test cli::tests::init_standalone ... ok

failures:

---- cli::tests::init_args_before_cmd stdout ----
PWD: C:\Users\peter\source\playdate\cargo\tests\crates\simple\no-cfg\tests/crates/simple/no-cfg
Error: The system cannot find the path specified. (os error 3)

Stack backtrace:
   0: std::backtrace_rs::backtrace::dbghelp64::trace
             at /rustc/faefc618cf48bd794cbc808448df1bf3f59f36af/library\std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:91
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/faefc618cf48bd794cbc808448df1bf3f59f36af/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2: std::backtrace::Backtrace::create
             at /rustc/faefc618cf48bd794cbc808448df1bf3f59f36af/library\std\src\backtrace.rs:331
   3: std::backtrace::Backtrace::capture
             at /rustc/faefc618cf48bd794cbc808448df1bf3f59f36af/library\std\src\backtrace.rs:296
   4: anyhow::error::impl$1::from<std::io::error::Error>
             at C:\Users\peter\.cargo\registry\src\index.crates.io-6f17d22bba15001f\anyhow-1.0.82\src\backtrace.rs:27
   5: core::result::impl$27::from_residual<tuple$<>,std::io::error::Error,anyhow::Error>
             at /rustc/faefc618cf48bd794cbc808448df1bf3f59f36af\library\core\src\result.rs:1964
   6: cargo_playdate::cli::tests::init_args_before_cmd
             at C:\Users\peter\source\playdate\cargo\src\cli\mod.rs:834
   7: cargo_playdate::cli::tests::init_args_before_cmd::closure$0
             at C:\Users\peter\source\playdate\cargo\src\cli\mod.rs:831
   8: core::ops::function::FnOnce::call_once<cargo_playdate::cli::tests::init_args_before_cmd::closure_env$0,tuple$<> >
             at /rustc/faefc618cf48bd794cbc808448df1bf3f59f36af\library\core\src\ops\function.rs:250
   9: core::ops::function::FnOnce::call_once
             at /rustc/faefc618cf48bd794cbc808448df1bf3f59f36af/library\core\src\ops\function.rs:250
  10: test::__rust_begin_short_backtrace<enum2$<core::result::Result<tuple$<>,alloc::string::String> >,enum2$<core::result::Result<tuple$<>,alloc::string::String> > (*)()>
             at /rustc/faefc618cf48bd794cbc808448df1bf3f59f36af/library\test\src\lib.rs:625
  11: test::run_test::closure$0
             at /rustc/faefc618cf48bd794cbc808448df1bf3f59f36af/library\test\src\lib.rs:569
  12: test::run_test::closure$1
             at /rustc/faefc618cf48bd794cbc808448df1bf3f59f36af/library\test\src\lib.rs:599
  13: std::sys_common::backtrace::__rust_begin_short_backtrace<test::run_test::closure_env$1,tuple$<> >
             at /rustc/faefc618cf48bd794cbc808448df1bf3f59f36af/library\std\src\sys_common\backtrace.rs:155
  14: std::thread::impl$0::spawn_unchecked_::closure$2::closure$0
             at /rustc/faefc618cf48bd794cbc808448df1bf3f59f36af/library\std\src\thread\mod.rs:542
  15: core::panic::unwind_safe::impl$25::call_once
             at /rustc/faefc618cf48bd794cbc808448df1bf3f59f36af/library\core\src\panic\unwind_safe.rs:272
  16: std::panicking::try::do_call
             at /rustc/faefc618cf48bd794cbc808448df1bf3f59f36af/library\std\src\panicking.rs:559
  17: std::panicking::try
             at /rustc/faefc618cf48bd794cbc808448df1bf3f59f36af/library\std\src\panicking.rs:523
  18: std::panic::catch_unwind
             at /rustc/faefc618cf48bd794cbc808448df1bf3f59f36af/library\std\src\panic.rs:149
  19: std::thread::impl$0::spawn_unchecked_::closure$2
             at /rustc/faefc618cf48bd794cbc808448df1bf3f59f36af/library\std\src\thread\mod.rs:541
  20: core::ops::function::FnOnce::call_once<std::thread::impl$0::spawn_unchecked_::closure_env$2<test::run_test::closure_env$1,tuple$<> >,tuple$<> >
             at /rustc/faefc618cf48bd794cbc808448df1bf3f59f36af/library\core\src\ops\function.rs:250
  21: alloc::boxed::impl$48::call_once
             at /rustc/faefc618cf48bd794cbc808448df1bf3f59f36af/library\alloc\src\boxed.rs:2022
  22: alloc::boxed::impl$48::call_once
             at /rustc/faefc618cf48bd794cbc808448df1bf3f59f36af/library\alloc\src\boxed.rs:2022
  23: std::sys::pal::windows::thread::impl$0::new::thread_start
             at /rustc/faefc618cf48bd794cbc808448df1bf3f59f36af/library\std\src\sys\pal\windows\thread.rs:52
  24: BaseThreadInitThunk
  25: RtlUserThreadStart

failures:
    cli::tests::init_args_before_cmd

test result: FAILED. 12 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.27s
</pre>
</details>

**Comment by boozook** [comment]
Thank you!

**Comment by boozook** [comment]
> I think CLI tests are not being run under CI.

That's strange, I'll check it out.
