### ISSUE TITLE
Unexpected `overlapping_sprites` behavior

### ISSUE THREAD

**Issue by paulstraw** [boozook/playdate#412]
I'm running into some unexpected behavior with `overlapping_sprites`, and set up a minimal repro here: https://github.com/paulstraw/bzpd-overlapping-sprites/blob/main/src/lib.rs#L106-L108. Specifically:

1. It panics if no sprites overlap (or if the sprite has no collide rect set).
2. It leaks memory when other sprites do overlap.

**Comment by boozook** [comment]
Yup. Thanks! According to [documentation](https://github.com/boozook/playdate/blob/main/api/sys/gen/pd2.5.0-pd-111111110.rs#L3995)
> The caller is responsible for freeing the returned array

we have to dealloc it, not just borrow.

So, also need to check and fix same for
- [ ] `checkCollisions`
- [ ] `moveWithCollisions`
- [ ] `querySpritesAtPoint`
- [ ] `querySpritesInRect`
- [ ] `querySpritesAlongLine`
- [ ] `querySpriteInfoAlongLine`
- [ ] _`overlappingSprites`_
- [ ] `allOverlappingSprites`

**Comment by boozook** [comment]
Fixed in #413

<img width="744" alt="Screenshot 2024-08-24 at 22 28 08" src="https://github.com/user-attachments/assets/643a63ab-e0fe-44f9-8bb7-dcbad88c3381">
